version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  #install:
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - export REPOSITORY_URI="211125636620.dkr.ecr.ap-south-1.amazonaws.com/test-deploy"
      - aws ecr get-login-password --region REGION| docker login --username AWS --password-stdin 211125636620.dkr.ecr.ap-south-1.amazonaws.com/test-deploy
      - export TAG=$(aws ecr describe-images --repository-name test-deploy --region REGION --query "sort_by(imageDetails,&  imagePushedAt)[*].imageTags[*]" --output text | tail -1)
      # - command
  build:
    commands:
      # - command
  post_build:
    commands:
      - printf '[{"name":"test-deploy","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > imagedefinitions.json
      - cat imagedefinitions.json
      # - command
artifacts:
  files: imagedefinitions.json
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths